name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.0, v1.2.3 etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE using PyInstaller
        run: pyinstaller --onefile PDF.py

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/PDF.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
